name: main

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  main:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node and application
        uses: ./.github/actions/setup

      - name: type check
        run: yarn typecheck

      - name: linters check
        run: |
          yarn lint

      - name: run test
        run: |
          yarn test

      - name: check if successfully build application
        run: |
          yarn build

  deploy:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs: main
    steps:
      - name: deploy to application
        run: echo "[FIXME] ここでデプロイ処理を実行する"
